const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BACKEND_PUBLIC='https://wedontcarecars.com';
let session=null, role='dealer', inventory=[], editing=null, existingPhotos=[], localPhotos=[], primaryKey=null, busy=false, lastBackupStatus=null, localSaveTimer=null;
const route=()=>location.pathname.replace(/\/$/,'')||'/';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>'$'+Number(v||0).toLocaleString();
const title=v=>[v.year,v.make,v.model,v.trim].filter(Boolean).join(' ')||'Incomplete vehicle';
const roleOf=j=>String(j?.role||j?.user?.role||j?.session?.role||'dealer').toLowerCase().includes('admin')?'admin':'dealer';
const LOCAL_DB='wdcc-dealer-local-safety',LOCAL_STORE='vehicle-drafts',LOCAL_TTL=30*24*60*60*1000;
function openLocalDb(){return new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('indexeddb_unavailable'));const r=indexedDB.open(LOCAL_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(LOCAL_STORE))r.result.createObjectStore(LOCAL_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('indexeddb_open_failed'))})}
async function localPut(key,value){try{const db=await openLocalDb();await new Promise((resolve,reject)=>{const tx=db.transaction(LOCAL_STORE,'readwrite');tx.objectStore(LOCAL_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch{try{localStorage.setItem(`${LOCAL_DB}:${key}`,JSON.stringify({...value,photoFiles:[]}));return true}catch{return false}}}
async function localGet(key){try{const db=await openLocalDb();const value=await new Promise((resolve,reject)=>{const tx=db.transaction(LOCAL_STORE,'readonly'),r=tx.objectStore(LOCAL_STORE).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return value}catch{try{return JSON.parse(localStorage.getItem(`${LOCAL_DB}:${key}`)||'null')}catch{return null}}}
async function localDelete(key){try{const db=await openLocalDb();await new Promise((resolve,reject)=>{const tx=db.transaction(LOCAL_STORE,'readwrite');tx.objectStore(LOCAL_STORE).delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{}try{localStorage.removeItem(`${LOCAL_DB}:${key}`)}catch{}}
function localKey(id=editing?.id||'new'){return `vehicle:${id||'new'}`}
async function saveLocalDraft(synced=false){if(!$('#vehicleForm'))return false;const value={schemaVersion:1,savedAt:new Date().toISOString(),synced,vehicleId:editing?.id||null,form:currentForm(),existingPhotos:[...existingPhotos],primaryKey,photoFiles:localPhotos.map(x=>x.file).filter(Boolean)};return localPut(localKey(),value)}
function queueLocalDraft(){clearTimeout(localSaveTimer);localSaveTimer=setTimeout(()=>saveLocalDraft(false).catch(()=>{}),350)}
async function restoreLocalDraft(id='new'){const value=await localGet(localKey(id));if(!value||!value.savedAt)return;if(Date.now()-Date.parse(value.savedAt)>LOCAL_TTL){await localDelete(localKey(id));return}if(id!=='new'&&editing?.updatedAt&&Date.parse(value.savedAt)<=Date.parse(editing.updatedAt))return;for(const [key,val] of Object.entries(value.form||{})){const el=$(`[name=${key}]`);if(el&&String(el.value||'').trim()==='')el.value=val??''}if(Array.isArray(value.existingPhotos)&&!existingPhotos.length)existingPhotos=value.existingPhotos.filter(Boolean);if(Array.isArray(value.photoFiles)){for(const file of value.photoFiles){if(file instanceof Blob)localPhotos.push({file,url:URL.createObjectURL(file)})}}primaryKey=value.primaryKey||primaryKey;renderPhotos();renderSidePreview();updateReadiness();toast('Recovered the locally saved vehicle draft.')}
function noteBackup(value){
  if(!value?.status)return;
  const priority={failed:3,not_configured:2,verified:1};
  if(!lastBackupStatus||(priority[value.status]||0)>=(priority[lastBackupStatus.status]||0))lastBackupStatus=value;
}
function backupMessage(){if(lastBackupStatus?.status==='verified')return ' Primary save and Drive backup verified.';if(lastBackupStatus?.status==='failed')return ' Primary save completed; Drive backup needs retry.';if(lastBackupStatus?.status==='not_configured')return ' Primary save completed; Drive backup is not configured.';return ''}
async function api(p,o={}){const h={...(o.headers||{})};if(o.body&&!(o.body instanceof Blob)&&typeof o.body!=='string'){o.body=JSON.stringify(o.body);h['content-type']='application/json'}const r=await fetch(p,{credentials:'include',...o,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok){const e=new Error(j.error||`HTTP ${r.status}`);e.status=r.status;e.data=j;throw e}return j}
function toast(msg){document.querySelector('.toast')?.remove();const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),3400)}
function statusClass(s){return ['published','draft','pending_review','archived'].includes(s)?s:''}
function nav(active){return `<div class="shell"><aside class="side"><div class="nav-title">Operations</div><a class="nav ${active==='dashboard'?'active':''}" href="/${role}/dashboard">Dashboard</a><a class="nav ${active==='inventory'?'active':''}" href="/${role}/inventory">Inventory</a><a class="nav ${active==='editor'?'active':''}" href="/${role}/inventory/new">Add Vehicle</a>${role==='admin'?`<a class="nav ${active==='review'?'active':''}" href="/admin/review">Admin Review</a>`:''}</aside><main class="main" id="main"></main></div>`}
function showAccount(){const a=$('#account');if(a){a.classList.remove('hidden');$('#who').textContent=(role==='admin'?'Admin':'Dealer')+' session'}}
function cleanInventory(a){return (Array.isArray(a)?a:(a?.items||a?.vehicles||a?.data||[])).filter(Boolean)}
async function loadInventory(){const j=await api('/api/inventory');inventory=cleanInventory(j);return inventory}
async function requireSession(){try{const j=await api('/api/auth/session');if(!j?.authenticated)throw new Error('unauthenticated');session=j;role=roleOf(j);return true}catch{return false}}
function loginPage(){const wantAdmin=route().startsWith('/admin');$('#account')?.classList.add('hidden');$('#app').innerHTML=`<main class="login-shell"><form class="login-card" id="loginForm"><div class="eyebrow">WDCC Secure Operations</div><h1>${wantAdmin?'Admin':'Dealer'} Sign In</h1><p>Inventory, photos, drafts, previews and publishing.</p><div class="role-tabs"><a class="role-tab ${!wantAdmin?'active':''}" href="/dealer/login">Dealer</a><a class="role-tab ${wantAdmin?'active':''}" href="/admin/login">Admin</a></div><div class="field"><label>Username / Email</label><input name="email" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn primary" style="width:100%" type="submit">Sign In</button><div class="msg" id="loginMsg"></div></form></main>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();const m=$('#loginMsg');m.className='msg';m.textContent='Signing in…';const d=Object.fromEntries(new FormData(e.currentTarget));try{const j=await api('/api/auth/login',{method:'POST',body:d});const r=roleOf(j);if(wantAdmin&&r!=='admin')throw new Error('Admin account required');location.href=r==='admin'?'/admin/dashboard':'/dealer/dashboard'}catch(x){m.className='msg bad';m.textContent=x.message}}}
function dashboard(){showAccount();$('#app').innerHTML=nav('dashboard');const active=inventory.filter(x=>x.status!=='archived');const pub=inventory.filter(x=>x.status==='published');const draft=inventory.filter(x=>x.status==='draft');const review=inventory.filter(x=>x.status==='pending_review');$('#main').innerHTML=`<div class="page-head"><div><div class="eyebrow">Inventory Operations</div><h1>Dashboard</h1></div><div class="head-actions"><a class="btn primary" href="/${role}/inventory/new">Add Vehicle</a></div></div><div class="kpis"><div class="card kpi"><span>Active Vehicles</span><strong>${active.length}</strong></div><div class="card kpi"><span>Published</span><strong>${pub.length}</strong></div><div class="card kpi"><span>Drafts</span><strong>${draft.length}</strong></div><div class="card kpi"><span>Pending Review</span><strong>${review.length}</strong></div></div><div class="card section"><h2>Recent Inventory</h2>${rows(active.slice(0,8))}</div>`;wireRows()}
function rows(list){if(!list.length)return '<div class="empty">No vehicles in this view.</div>';return `<div class="inventory-list"><div class="inv-head"><div>Vehicle</div><div>Price</div><div>Status</div><div>Updated</div><div></div></div>${list.map(v=>`<div class="inv-row" data-id="${esc(v.id)}"><div class="vehicle-title"><b>${esc(title(v))}</b><small>${esc(v.stock||'No stock #')} · ${Number(v.mileage||0).toLocaleString()} mi</small></div><div><b>${cash(v.price)}</b></div><div><span class="status ${statusClass(v.status)}">${esc(v.status||'draft')}</span></div><div><small>${v.updatedAt?new Date(v.updatedAt).toLocaleDateString():'—'}</small></div><div class="row-actions"><button class="btn small" data-action="preview">Preview</button><a class="btn small" href="/${role}/inventory/${encodeURIComponent(v.id)}/edit">Edit</a>${v.status==='archived'?`<button class="btn small blue" data-action="restore">Restore</button>`:`<button class="btn small ${v.status==='published'?'':'primary'}" data-action="publish">${v.status==='published'?'Published':'Publish'}</button><button class="btn small danger" data-action="delete">Delete</button>`}</div></div>`).join('')}</div>`}
function inventoryPage(){showAccount();$('#app').innerHTML=nav('inventory');const active=inventory.filter(v=>v.status!=='archived');const archived=inventory.filter(v=>v.status==='archived');$('#main').innerHTML=`<div class="page-head"><div><div class="eyebrow">Manage Vehicles</div><h1>Inventory</h1></div><div class="head-actions"><button class="btn desktop-only" id="showArchive">Archived (${archived.length})</button><a class="btn primary" href="/${role}/inventory/new">Add Vehicle</a></div></div><div class="card" id="inventoryRows">${rows(active)}</div>`;wireRows();$('#showArchive').onclick=()=>{$('#inventoryRows').innerHTML=rows(archived);wireRows()}}
function reviewPage(){showAccount();if(role!=='admin')return location.replace('/dealer/dashboard');$('#app').innerHTML=nav('review');const list=inventory.filter(v=>v.status==='pending_review');$('#main').innerHTML=`<div class="page-head"><div><div class="eyebrow">Admin</div><h1>Review Queue</h1></div></div><div class="card">${rows(list)}</div>`;wireRows()}
async function wireRows(){$$('[data-action]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;const row=b.closest('[data-id]'),id=row.dataset.id,act=b.dataset.action;try{b.disabled=true;if(act==='preview'){const j=await api('/api/inventory/'+encodeURIComponent(id));showPreview(j.item||j)}else if(act==='delete'){if(confirm('Delete this listing? It will be archived and removed from active inventory.')){await api('/api/inventory/'+encodeURIComponent(id),{method:'DELETE'});toast('Vehicle deleted from active inventory.');await refreshPage()}}else if(act==='restore'){await api('/api/inventory/'+encodeURIComponent(id),{method:'PATCH',body:{status:'draft'}});toast('Vehicle restored as draft.');await refreshPage()}else if(act==='publish'){if((row.querySelector('.status')?.textContent||'').trim()==='published')return;await publishId(id);await refreshPage()}}catch(x){toast('Action failed: '+x.message)}finally{b.disabled=false}})}
async function publishId(id){try{await api('/api/inventory/'+encodeURIComponent(id),{method:'PATCH',body:{status:'published',featured:true}});toast('Vehicle published.')}catch(x){if(role!=='admin'&&(x.status===401||x.status===403)){await api('/api/inventory/'+encodeURIComponent(id),{method:'PATCH',body:{status:'pending_review',featured:true,submitForReview:true}});toast('Submitted for admin review.')}else throw x}}
function currentForm(){const f=Object.fromEntries(new FormData($('#vehicleForm')));for(const k of ['year','price','downPayment','mileage'])f[k]=Number(f[k]||0);f.features=[];f.badges=[];f.location='Tampa Bay';f.condition=f.condition||'Used';return f}
function photoUrl(p){const u=typeof p==='string'?p:(p?.url||'');return /^https?:\/\//i.test(u)?u:''}
function allPhotoObjects(){return [...existingPhotos.map((url,i)=>({key:'remote:'+i,url,remote:true})),...localPhotos.map((x,i)=>({key:'local:'+i,url:x.url,file:x.file,remote:false}))]}
function renderPhotos(){const g=$('#photoGrid');if(!g)return;const ps=allPhotoObjects();if(!primaryKey&&ps[0])primaryKey=ps[0].key;g.innerHTML=ps.map(p=>`<div class="photo ${p.key===primaryKey?'primary':''}" data-key="${p.key}">${photoUrl(p.url)?`<img src="${esc(p.url)}" alt="Vehicle photo">`:'<div style="display:grid;place-items:center;height:100%;font-size:11px;color:#778899">Stored photo</div>'}${p.key===primaryKey?'<span class="mark">PRIMARY</span>':''}<div class="tools"><button type="button" data-photo-primary>Primary</button><button type="button" class="remove" data-photo-remove>Remove</button></div></div>`).join('')||'<div class="empty" style="grid-column:1/-1">No photos selected yet.</div>';$$('[data-photo-primary]').forEach(b=>b.onclick=()=>{primaryKey=b.closest('.photo').dataset.key;renderPhotos();renderSidePreview();queueLocalDraft()});$$('[data-photo-remove]').forEach(b=>b.onclick=()=>{const key=b.closest('.photo').dataset.key;if(key.startsWith('remote:')){const idx=Number(key.split(':')[1]);existingPhotos.splice(idx,1)}else{const idx=Number(key.split(':')[1]);URL.revokeObjectURL(localPhotos[idx]?.url||'');localPhotos.splice(idx,1)}primaryKey=null;renderPhotos();renderSidePreview();queueLocalDraft()})}
function addFiles(files){for(const file of [...files]){if(!(String(file.type||'').startsWith('image/')||/\.(jpe?g|png|webp|avif|heic|heif)$/i.test(file.name||'')))continue;localPhotos.push({file,url:URL.createObjectURL(file)})}renderPhotos();renderSidePreview();queueLocalDraft()}
function editorTemplate(v={}){return `<div class="page-head"><div><div class="eyebrow">${v.id?'Edit Vehicle':'New Vehicle'}</div><h1>${v.id?esc(title(v)):'Add Vehicle'}</h1></div><div class="head-actions"><a class="btn" href="/${role}/inventory">Back to Inventory</a></div></div><div class="editor-grid"><div><form id="vehicleForm"><section class="card section"><h2>Vehicle Information</h2><div class="form-grid">${field('vin','VIN',v.vin)}${field('year','Year',v.year,'number')}${field('make','Make',v.make)}${field('model','Model',v.model)}${field('trim','Trim',v.trim)}${field('stock','Stock #',v.stock)}${field('price','Price',v.price,'number')}${field('downPayment','Down Payment',v.downPayment,'number')}${field('mileage','Mileage',v.mileage,'number')}${field('bodyStyle','Body Style',v.bodyStyle)}${field('transmission','Transmission',v.transmission)}${field('drivetrain','Drivetrain',v.drivetrain)}${field('fuelType','Fuel Type',v.fuelType||v.fuel)}${field('exteriorColor','Exterior Color',v.exteriorColor)}${field('interiorColor','Interior Color',v.interiorColor)}<div class="field full"><label>Description</label><textarea name="description">${esc(v.description||'')}</textarea></div></div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn" id="decodeVin" type="button">Decode VIN</button><span class="msg" id="editMsg"></span></div></section><section class="card section"><h2>Photos</h2><div class="photo-tools"><label class="upload-choice">Take Photo<input id="cameraInput" type="file" accept="image/*" capture="environment"></label><label class="upload-choice">Upload Photos<input id="galleryInput" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple></label></div><div class="drop" id="dropZone">Drop photos here or use the buttons above.</div><div class="photo-grid" id="photoGrid"></div></section></form></div><aside class="card sidecard"><div class="eyebrow">Listing Readiness</div><h2 style="margin:4px 0"><span id="readyPct">0</span>% ready</h2><div class="readiness"><span id="readyBar"></span></div><div class="checklist" id="checklist"></div><div class="editor-actions"><button class="btn" id="previewBtn" type="button">Preview</button><button class="btn" id="saveDraft" type="button">Save Draft</button><button class="btn primary wide" id="publishBtn" type="button">Publish / Submit</button>${v.id?'<button class="btn danger" id="deleteBtn" type="button">Delete</button>':''}</div><div class="preview-card" id="sidePreview"></div><div class="note">Delete is recoverable: the vehicle is archived and removed from active inventory. Admin can restore it later.</div></aside></div><div class="mobilebar"><button class="btn" id="mPreview" type="button">PREVIEW</button><button class="btn" id="mDraft" type="button">SAVE DRAFT</button><button class="btn primary" id="mPublish" type="button">PUBLISH</button></div>`}
function field(n,l,v='',type='text'){return `<div class="field"><label>${l}</label><input name="${n}" data-f="${n}" type="${type}" value="${esc(v??'')}"></div>`}
async function editorPage(id){showAccount();$('#app').innerHTML=nav('editor');editing=null;existingPhotos=[];localPhotos=[];primaryKey=null;lastBackupStatus=null;let v={};if(id){const j=await api('/api/inventory/'+encodeURIComponent(id));v=j.item||j;editing={...v,uploadCapability:j.uploadCapability||v.uploadCapability||''};existingPhotos=(v.photoPathnames||[]).filter(Boolean);const pi=existingPhotos.indexOf(v.primaryPhotoPathname);if(pi>=0)primaryKey='remote:'+pi}$('#main').innerHTML=editorTemplate(v);renderPhotos();wireEditor();renderSidePreview();updateReadiness();await restoreLocalDraft(id||'new')}
function wireEditor(){const form=$('#vehicleForm');form.addEventListener('input',()=>{renderSidePreview();updateReadiness();queueLocalDraft()});$('#cameraInput').onchange=e=>addFiles(e.target.files);$('#galleryInput').onchange=e=>addFiles(e.target.files);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('over')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('over')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('#decodeVin').onclick=decodeVin;$('#previewBtn').onclick=()=>showPreview({...editing,...currentForm(),photoPathnames:allPhotoUrls(),primaryPhotoPathname:primaryPhotoUrl()});$('#saveDraft').onclick=()=>saveVehicle('draft');$('#publishBtn').onclick=()=>saveVehicle('publish');$('#deleteBtn')&&($('#deleteBtn').onclick=deleteCurrent);$('#mPreview').onclick=$('#previewBtn').onclick;$('#mDraft').onclick=$('#saveDraft').onclick;$('#mPublish').onclick=$('#publishBtn').onclick}
async function decodeVin(){const m=$('#editMsg'),vin=String($('[name=vin]').value||'').toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,'').slice(0,17);$('[name=vin]').value=vin;if(vin.length!==17){m.className='msg bad';m.textContent='VIN must be 17 characters.';return}m.className='msg';m.textContent='Decoding…';try{const j=await api('/api/intake/vin/decode',{method:'POST',body:{vin}}),d=j.vehicle||j.data||{};for(const k of ['year','make','model','trim','bodyStyle','transmission','drivetrain','fuelType']){const el=$(`[name=${k}]`);if(el&&d[k])el.value=d[k]}m.className='msg good';m.textContent='VIN decoded. Confirm the fields before saving.';renderSidePreview();updateReadiness()}catch(x){m.className='msg bad';m.textContent='VIN decode failed: '+x.message}}
function primaryPhotoUrl(){const ps=allPhotoObjects(),p=ps.find(x=>x.key===primaryKey)||ps[0];return p?.url||null}
function allPhotoUrls(){return allPhotoObjects().map(x=>x.url).filter(u=>/^https?:\/\//i.test(u))}
async function ensureRecord(status='draft'){const data={...currentForm(),status,featured:true,submitForReview:false,photoPathnames:existingPhotos,primaryPhotoPathname:existingPhotos[0]||null};let j;if(editing?.id){j=await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'PATCH',body:data});noteBackup(j.backup);editing={...editing,...(j.item||j)}}else{j=await api('/api/inventory',{method:'POST',body:data});noteBackup(j.backup);editing={...(j.item||j),uploadCapability:j.uploadCapability||j.item?.uploadCapability||''};if(!editing.id)throw new Error('Vehicle ID missing after save')}if(!editing.uploadCapability&&editing.id){const fresh=await api('/api/inventory/'+encodeURIComponent(editing.id));editing={...editing,...(fresh.item||fresh),uploadCapability:fresh.uploadCapability||fresh.item?.uploadCapability||editing.uploadCapability}}return editing}
async function uploadPending(){if(!localPhotos.length)return;await ensureRecord('draft');if(!editing.uploadCapability)throw new Error('Photo upload capability is unavailable. Save/reopen the vehicle and try again.');const newUrls=[];for(let i=0;i<localPhotos.length;i++){const p=localPhotos[i];$('#editMsg').className='msg';$('#editMsg').textContent=`Uploading photo ${i+1} of ${localPhotos.length}…`;const r=await uploadPhoto(p.file,editing.id,editing.uploadCapability);noteBackup(r.backup);newUrls.push(r.url)}const remoteBefore=[...existingPhotos];existingPhotos=[...remoteBefore,...newUrls];if(primaryKey?.startsWith('local:')){const idx=Number(primaryKey.split(':')[1]);primaryKey='remote:'+(remoteBefore.length+idx)}localPhotos.forEach(x=>URL.revokeObjectURL(x.url));localPhotos=[];renderPhotos()}
async function decodeImageFile(file){if(typeof createImageBitmap==='function'){try{const bitmap=await createImageBitmap(file);return {source:bitmap,width:bitmap.width,height:bitmap.height,cleanup:()=>bitmap.close?.()}}catch{}}const objectUrl=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=()=>reject(new Error('This image format cannot be decoded on this device.'));el.src=objectUrl});return {source:img,width:img.naturalWidth||img.width,height:img.naturalHeight||img.height,cleanup:()=>URL.revokeObjectURL(objectUrl)}}catch(error){URL.revokeObjectURL(objectUrl);throw error}}
async function uploadPhoto(file,id,cap){const MAX=4000000;let blob=file,name=file.name;if(file.size>MAX||!['image/jpeg','image/webp'].includes(file.type)){const decoded=await decodeImageFile(file);try{let scale=Math.min(1,2200/Math.max(decoded.width,decoded.height)),w=Math.max(1,Math.round(decoded.width*scale)),h=Math.max(1,Math.round(decoded.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});if(!ctx)throw new Error('Photo optimization is unavailable on this device.');ctx.drawImage(decoded.source,0,0,w,h);blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Photo optimization failed')),'image/jpeg',.78));name=(file.name.replace(/\.[^.]+$/,'')||'vehicle-photo')+'.jpg'}finally{decoded.cleanup()}}if(blob.size>MAX)throw new Error('Photo is still too large after optimization.');const r=await fetch('/api/media-upload?vehicleId='+encodeURIComponent(id)+'&name='+encodeURIComponent(name),{method:'POST',credentials:'include',headers:{'content-type':blob.type||'image/jpeg','x-wdcc-upload-capability':cap},body:blob});const j=await r.json().catch(()=>({}));if(!r.ok||!j.url)throw new Error(j.error||`Photo upload HTTP ${r.status}`);return j}
async function saveVehicle(mode){if(busy)return;busy=true;const m=$('#editMsg');m.className='msg';m.textContent=mode==='draft'?'Saving draft…':'Preparing listing…';try{await ensureRecord('draft');await uploadPending();const photoUrls=[...existingPhotos];const pObj=allPhotoObjects().find(x=>x.key===primaryKey),primary=(pObj?.remote?pObj.url:null)||photoUrls[0]||null;const patch={...currentForm(),photoPathnames:photoUrls,primaryPhotoPathname:primary,featured:true};if(mode==='draft'){patch.status='draft';patch.submitForReview=false;const saved=await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'PATCH',body:patch});noteBackup(saved.backup);m.className='msg good';m.textContent='Draft saved.'+backupMessage();toast('Draft saved.')}else{const staged=await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'PATCH',body:{...patch,status:'draft'}});noteBackup(staged.backup);try{const published=await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'PATCH',body:{status:'published',featured:true,submitForReview:false}});noteBackup(published.backup);m.className='msg good';m.textContent='Published.'+backupMessage();toast('Vehicle published.')}catch(x){if(role!=='admin'&&(x.status===401||x.status===403)){const reviewed=await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'PATCH',body:{status:'pending_review',featured:true,submitForReview:true}});noteBackup(reviewed.backup);m.className='msg good';m.textContent='Submitted for admin review.'+backupMessage();toast('Submitted for admin review.')}else throw x}}await localDelete(localKey('new'));await saveLocalDraft(true);await loadInventory();setTimeout(()=>location.href=`/${role}/inventory`,850)}catch(x){m.className='msg bad';m.textContent='Save failed: '+x.message;toast('Save failed: '+x.message)}finally{busy=false}}
async function deleteCurrent(){if(!editing?.id)return;if(!confirm('Delete this listing? It will be archived and removed from active inventory.'))return;try{await api('/api/inventory/'+encodeURIComponent(editing.id),{method:'DELETE'});toast('Vehicle deleted from active inventory.');setTimeout(()=>location.href=`/${role}/inventory`,350)}catch(x){toast('Delete failed: '+x.message)}}
function renderSidePreview(){const c=$('#sidePreview');if(!c)return;const v={...editing,...currentForm()},p=primaryPhotoUrl();c.innerHTML=`<div class="preview-img">${p?`<img src="${esc(p)}">`:'Vehicle preview'}</div><div class="preview-copy"><h3>${esc(title(v))}</h3><strong>${cash(v.price)}</strong><div style="font-size:11px;color:#667788;margin-top:4px">${cash(v.downPayment)} down · ${Number(v.mileage||0).toLocaleString()} mi</div></div>`}
function updateReadiness(){if(!$('#vehicleForm'))return;const v=currentForm(),photos=allPhotoObjects().length,checks=[['Year / Make / Model',!!(v.year&&v.make&&v.model)],['Price',v.price>0],['Mileage',v.mileage>=0],['Photos',photos>0],['Description',String(v.description||'').trim().length>=10]];const pct=Math.round(checks.filter(x=>x[1]).length/checks.length*100);$('#readyPct').textContent=pct;$('#readyBar').style.width=pct+'%';$('#checklist').innerHTML=checks.map(x=>`<div class="check"><span>${x[0]}</span><b class="${x[1]?'ok':''}">${x[1]?'✓':'—'}</b></div>`).join('')}
function showPreview(v){document.querySelector('.modal')?.remove();const p=primaryPhotoUrl()||v.primaryPhotoPathname||(v.photoPathnames||[])[0]||'';const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box"><div class="modal-top"><b>Customer Listing Preview</b><button class="btn small" id="closePreview">Close</button></div><div class="modal-body"><div class="listing-preview"><div class="hero">${photoUrl(p)?`<img src="${esc(p)}">`:'No vehicle photo yet'}</div><div><div class="eyebrow">WDCC · Tampa Bay</div><h2>${esc(title(v))}</h2><div class="price">${cash(v.price)}</div><p><b>${cash(v.downPayment)} down</b></p><div class="specs"><div class="spec"><b>Mileage</b><br>${Number(v.mileage||0).toLocaleString()}</div><div class="spec"><b>Stock</b><br>${esc(v.stock||'—')}</div><div class="spec"><b>Drive</b><br>${esc(v.drivetrain||'—')}</div><div class="spec"><b>Condition</b><br>${esc(v.condition||'Used')}</div></div><p style="line-height:1.55;color:#536474">${esc(v.description||'No description added yet.')}</p></div></div></div></div>`;document.body.appendChild(m);$('#closePreview').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
async function refreshPage(){await loadInventory();const p=route();if(p.endsWith('/inventory'))inventoryPage();else if(p.endsWith('/review'))reviewPage();else dashboard()}
async function boot(){const p=route();if(p.endsWith('/login')||p==='/'){loginPage();return}if(!(await requireSession())){location.replace(p.startsWith('/admin')?'/admin/login':'/dealer/login');return}showAccount();await loadInventory();if(p==='/admin/review')return reviewPage();const em=p.match(/^\/(dealer|admin)\/inventory\/([^/]+)\/edit$/);if(em)return editorPage(decodeURIComponent(em[2]));if(p.endsWith('/inventory/new'))return editorPage(null);if(p.endsWith('/inventory'))return inventoryPage();dashboard()}
$('#signOut').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.replace('/dealer/login')};boot();
