"use client";

import Link from "next/link";
import {DragEvent,useEffect,useMemo,useState} from "react";
import DealerNav from "../../DealerNav";

type Row=Record<string,string>;
const fields=["year","make","model","trim","price","downPayment","mileage","stock","vin","bodyStyle","condition","transmission","exteriorColor","interiorColor","drivetrain","fuelType","description"];
const aliases:Record<string,string[]>={year:["year","yr"],make:["make","manufacturer"],model:["model"],trim:["trim"],price:["price","cash price","cashprice"],downPayment:["down payment","downpayment","down_payment","down"],mileage:["mileage","miles","odometer"],stock:["stock","stock #","stock number","stocknumber"],vin:["vin"],bodyStyle:["body style","bodystyle","body"],condition:["condition"],transmission:["transmission","trans"],exteriorColor:["exterior color","exteriorcolor","exterior"],interiorColor:["interior color","interiorcolor","interior"],drivetrain:["drivetrain","drive train","drive"],fuelType:["fuel type","fueltype","fuel"],description:["description","desc"]};
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell.trim());cell=""}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell="";if(row.some(Boolean))rows.push(row);row=[]}else cell+=c}if(cell||row.length){row.push(cell.trim());if(row.some(Boolean))rows.push(row)}return rows}
const norm=(v:string)=>v.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");

export default function ImportVehicles(){
 const[ready,setReady]=useState(false),[step,setStep]=useState(1),[name,setName]=useState(""),[headers,setHeaders]=useState<string[]>([]),[raw,setRaw]=useState<string[][]>([]),[map,setMap]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[imported,setImported]=useState(0);
 useEffect(()=>{fetch("/api/auth/session",{cache:"no-store",credentials:"include"}).then(r=>r.json()).then(s=>{if(!s.authenticated)location.href="/dealer";else setReady(true)}).catch(()=>location.href="/dealer")},[]);
 function loadFile(file:File){setName(file.name);file.text().then(text=>{const parsed=parseCsv(text);if(parsed.length<2)throw Error("The file needs a header row and at least one vehicle.");const h=parsed[0].map(x=>x.trim()),rows=parsed.slice(1);setHeaders(h);setRaw(rows);const auto:Record<string,string>={};for(const f of fields){const hit=h.find(x=>aliases[f]?.includes(norm(x)));if(hit)auto[f]=hit}setMap(auto);setStep(2);setMessage("")}).catch(e=>setMessage(e.message||"Could not read CSV"))}
 function drop(e:DragEvent<HTMLDivElement>){e.preventDefault();const file=e.dataTransfer.files?.[0];if(file)loadFile(file)}
 const rows=useMemo<Row[]>(()=>raw.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||""]))),[raw,headers]);
 const normalized=useMemo(()=>rows.map(row=>Object.fromEntries(fields.map(f=>[f,map[f]?row[map[f]]||"":""]))),[rows,map]);
 const errors=useMemo(()=>normalized.map((r:any,i)=>{const e:string[]=[];if(!Number(r.year))e.push("year");if(!String(r.make).trim())e.push("make");if(!String(r.model).trim())e.push("model");if(!Number(r.price))e.push("price");return {row:i+2,fields:e}}).filter(x=>x.fields.length),[normalized]);
 function template(){const csv="year,make,model,trim,price,downPayment,mileage,stock,vin,bodyStyle,condition,transmission,exteriorColor,interiorColor,drivetrain,fuelType,description\n2020,Dodge,Challenger,SXT,24995,2000,41000,WDCC-2020-001,,Coupe,Used,Automatic,Black,Black,RWD,Gasoline,Clean title. Runs and drives great.";const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="wdcc-import-template.csv";a.click();URL.revokeObjectURL(url)}
 async function runImport(){if(errors.length){setMessage("Fix required fields before importing.");return}setBusy(true);setImported(0);setMessage("Importing vehicles as drafts…");try{for(let i=0;i<normalized.length;i++){const r:any=normalized[i],body={year:Number(r.year),make:r.make.trim(),model:r.model.trim(),trim:r.trim.trim(),price:Number(r.price),downPayment:Number(r.downPayment||0),mileage:Number(r.mileage||0),stock:r.stock.trim(),vin:r.vin.trim(),bodyStyle:r.bodyStyle.trim(),condition:r.condition.trim()||"Used",transmission:r.transmission.trim(),exteriorColor:r.exteriorColor.trim(),interiorColor:r.interiorColor.trim(),drivetrain:r.drivetrain.trim(),fuelType:r.fuelType.trim(),description:r.description.trim(),status:"draft",internalOnly:false,visibility:"public"};const req=await fetch("/api/inventory",{method:"POST",credentials:"include",headers:{"content-type":"application/json","X-WDCC-Request-ID":crypto.randomUUID()},body:JSON.stringify(body)}),j=await req.json().catch(()=>({}));if(!req.ok||!j?.item?.id)throw Error(`Row ${i+2}: ${j.error||`HTTP ${req.status}`}`);setImported(i+1)}setStep(4);setMessage(`Imported ${normalized.length} vehicle${normalized.length===1?"":"s"} as drafts.`)}catch(e){setMessage(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 if(!ready)return <main className="wdccGate">Checking secure dealer session…</main>;
 return <main className="dcPage"><header className="dcTop"><Link className="brand" href="/dealer"><img src="/wdcc-official-logo.webp" alt="WDCC"/><span><b>WDCC · DEALER PORTAL</b><small>Inventory Operations</small></span></Link><a href="tel:18135164752">☎ (813) 516-4752</a></header><div className="dcShell"><aside className="dcSide"><DealerNav active="import"/></aside><section className="dcContent"><div className="dcTitle"><div><h1>Import Vehicles</h1><p>Import multiple vehicles at once. Every imported vehicle starts as a draft for review.</p></div><Link className="dcButton" href="/dealer/inventory">Cancel</Link></div><div className="dcCard"><div className="dcSteps">{["Upload File","Map Columns","Preview & Validate","Import"].map((label,i)=><div className={`dcStep${step===i+1?" active":""}${step>i+1?" done":""}`} key={label}><b>{i+1}</b><span>{label}</span></div>)}</div>
 {step===1&&<div className="dcDrop" onDragOver={e=>e.preventDefault()} onDrop={drop}><div><h3>Drag & drop your CSV file here</h3><p>or choose a file from your device. CSV only.</p><label className="dcButton dcPrimary">Choose File<input hidden type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)loadFile(f)}}/></label><p><button className="templateLink" onClick={template}>Download sample template</button></p></div></div>}
 {step===2&&<><h3>Map Columns</h3><p className="importHelp">File: <b>{name}</b>. Required fields are Year, Make, Model and Price.</p><div className="mapGrid">{fields.map(f=><label key={f}><span>{f}{["year","make","model","price"].includes(f)?" *":""}</span><select value={map[f]||""} onChange={e=>setMap(v=>({...v,[f]:e.target.value}))}><option value="">Not mapped</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className="dcActions"><button className="dcButton" onClick={()=>setStep(1)}>Back</button><button className="dcButton dcPrimary" onClick={()=>setStep(3)}>Preview & Validate</button></div></>}
 {step===3&&<><h3>Preview & Validate</h3><p className="importHelp">{normalized.length} row{normalized.length===1?"":"s"} detected. {errors.length?`${errors.length} row${errors.length===1?"":"s"} need attention.`:"All required fields are present."}</p>{errors.length>0&&<div className="dcError">{errors.slice(0,8).map(e=><div key={e.row}>Row {e.row}: missing/invalid {e.fields.join(", ")}</div>)}</div>}<div className="dcPreviewWrap"><table className="dcPreviewTable"><thead><tr><th>Row</th><th>Year</th><th>Make</th><th>Model</th><th>Price</th><th>Stock</th><th>Validation</th></tr></thead><tbody>{normalized.slice(0,20).map((r:any,i)=>{const err=errors.find(e=>e.row===i+2);return <tr key={i}><td>{i+2}</td><td>{r.year}</td><td>{r.make}</td><td>{r.model}</td><td>{r.price}</td><td>{r.stock}</td><td>{err?<span className="bad">Needs attention</span>:<span className="good">Ready</span>}</td></tr>})}</tbody></table></div><div className="dcActions"><button className="dcButton" onClick={()=>setStep(2)}>Back</button><button className="dcButton dcPrimary" disabled={busy||errors.length>0} onClick={runImport}>{busy?`Importing ${imported}/${normalized.length}…`:`Import ${normalized.length} as Drafts`}</button></div></>}
 {step===4&&<div className="importDone"><div className="doneIcon">✓</div><h2>Import complete</h2><p>{message}</p><div className="dcActions"><Link className="dcButton" href="/dealer/inventory">View All Vehicles</Link><Link className="dcButton dcPrimary" href="/dealer/inventory/new">Add Another Vehicle</Link></div></div>}
 {message&&step!==4&&<div className={message.toLowerCase().includes("fail")||message.toLowerCase().includes("fix")||message.toLowerCase().includes("row ")?"dcError":"dcSuccess"}>{message}</div>}</div></section></div><style jsx global>{css}</style></main>
}
const css=`
.importHelp{color:#697580;font-size:10px;margin:0 0 15px}.templateLink{border:0;background:transparent;color:#2772ad;text-decoration:underline;font-size:9px;cursor:pointer}.mapGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.mapGrid label{display:grid;gap:5px}.mapGrid span{font-size:8px;font-weight:900;color:#5e6b75}.mapGrid select{height:38px;border:1px solid #cbd4dc;border-radius:6px;background:#fff;color:#27333d;padding:0 8px}.bad{color:#b52532;font-weight:900}.good{color:#197a46;font-weight:900}.importDone{text-align:center;padding:32px 10px}.doneIcon{width:60px;height:60px;border-radius:50%;display:grid;place-items:center;margin:0 auto 12px;background:#e7f7ed;color:#17884b;font-size:30px;font-weight:950}.importDone h2{margin:0}.importDone p{color:#64717b}.importDone .dcActions{justify-content:center}@media(max-width:760px){.mapGrid{grid-template-columns:1fr 1fr}}@media(max-width:430px){.mapGrid{grid-template-columns:1fr}.dcCard{padding:13px}}
`;
