"use client";
import Link from"next/link";
import{useEffect,useState}from"react";

export function Intro(){const[done,setDone]=useState(false);useEffect(()=>{if(sessionStorage.getItem("wdcc_intro_seen")||window.matchMedia("(prefers-reduced-motion: reduce)").matches){setDone(true);return}sessionStorage.setItem("wdcc_intro_seen","1");const t=setTimeout(()=>setDone(true),2600);return()=>clearTimeout(t)},[]);if(done)return null;return <div className="cinematic" aria-hidden="true"><div className="cinSmoke one"/><div className="cinSmoke two"/><img className="cinLogo" src="/wdcc-official-logo.webp" alt=""/><div className="cinCar"><img src="https://wedontcarecars.com/assets/hero-car.webp" alt=""/></div><button className="skipIntro" onClick={()=>setDone(true)}>Skip intro</button></div>}

export function Header(){return <><div className="commandStrip"><div className="wrap"><span>Tampa Bay · In-house financing</span><span>Fast answers · Real inventory</span><span>Sean · <b>813-516-4752</b></span></div></div><header className="premiumHeader"><div className="wrap nav"><Link className="brand logoBrand" href="/" aria-label="We Don't Care Cars home"><img src="/wdcc-official-logo.webp" alt="We Don't Care Cars"/></Link><div className="navlinks"><Link href="/inventory">INVENTORY</Link><Link href="/schedule-test-drive">TEST DRIVE</Link><Link href="/get-approved">FINANCING</Link><Link href="/contact">CONTACT</Link><a className="premiumPhone" href="tel:+18135164752">SEAN · <b>813-516-4752</b></a><Link className="premiumApply" href="/get-approved">GET APPROVED</Link></div></div></header><div className="mobilebar"><a href="tel:+18135164752">CALL SEAN</a><Link href="/get-approved">FINANCING</Link><Link href="/inventory">INVENTORY</Link></div></>}

export function Footer(){return <footer className="premiumFooter"><div className="wrap premiumFooterRow"><div style={{display:"flex",alignItems:"center",gap:14}}><img src="/wdcc-official-logo.webp" alt="WDCC"/><div><strong>WE DON'T CARE CARS</strong><br/><small>Tampa Bay · Real inventory · Direct help</small></div></div><div><a href="tel:+18135164752">813-516-4752</a> · <Link href="/contact">Contact</Link></div></div></footer>}

export function VehicleGrid({limit}:{limit?:number}){const[items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/inventory",{cache:"no-store"}).then(r=>r.json()).then(j=>setItems((j.items||j.inventory||[]).filter((v:any)=>!v.status||String(v.status).toLowerCase()==="published"))).catch(()=>{}).finally(()=>setLoading(false))},[]);const shown=limit?items.slice(0,limit):items;if(loading)return <div className="grid">{[1,2,3].map(i=><div className="card" key={i}><div className="photo">LOADING VEHICLE…</div><div className="cardBody"><div className="carTitle">Inventory loading</div></div></div>)}</div>;return <div className="grid">{shown.length?shown.map(v=><article className="card" key={v.id}><Link className="photo" href={`/vehicle/${v.id}`} aria-label={`View ${v.year} ${v.make} ${v.model}`}>{v.primaryPhotoPathname?<img src={`/api/media?p=${encodeURIComponent(v.primaryPhotoPathname)}`} alt={`${v.year} ${v.make} ${v.model}`}/>:"PHOTOS COMING"}</Link><div className="cardBody"><div className="carTitle">{v.year} {v.make} {v.model}</div><div className="facts"><span>{Number(v.mileage||0).toLocaleString()} MI</span>{v.stock&&<span>STOCK {v.stock}</span>}</div><div className="price">${Number(v.price||0).toLocaleString()}</div>{v.downPayment!=null&&<div className="down">${Number(v.downPayment).toLocaleString()} estimated down</div>}<div className="cardButtons"><Link href={`/vehicle/${v.id}`}><span>VIEW VEHICLE</span></Link><Link href={`/get-approved?vehicle=${encodeURIComponent(v.id)}`}><span>GET APPROVED</span></Link></div></div></article>):<div><h3>Inventory is being updated.</h3><p className="muted">Call or text Sean for vehicles being prepared now.</p></div>}</div>}
