"use client";

import {useState} from "react";
import {getAttributionContext,trackEvent} from "./attribution";

type Kind="schedule"|"contact"|"approval";
export default function LeadForm({kind,source}:{kind:Kind;source?:string}){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const formEl=event.currentTarget;setBusy(true);setMessage("Sending…");const idempotencyKey=crypto.randomUUID();try{const form=new FormData(formEl);const body:any=Object.fromEntries(form.entries());const url=new URL(window.location.href);const qs=url.searchParams;const vehicle=qs.get("vehicle")||qs.get("vehicleId")||"";if(vehicle&&!body.vehicleInterest)body.vehicleInterest=vehicle;const attribution=getAttributionContext();const leadSource=(qs.get("source")||source||attribution.source||`cta-${kind}`).slice(0,80);const payload={...body,kind,consent:form.get("consent")==="on",source:leadSource,cta:source||`cta-${kind}`,sessionId:attribution.sessionId,anonymousUserId:attribution.anonymousUserId,referralCode:attribution.referralCode||undefined,landingPath:attribution.landingPath||undefined,vehicleId:vehicle||undefined,pagePath:url.pathname,referrer:attribution.referrer||document.referrer||undefined,utmSource:attribution.source||undefined,utmMedium:attribution.medium||undefined,utmCampaign:attribution.campaign||undefined,utmContent:attribution.content||undefined,utmTerm:attribution.term||undefined,clickId:attribution.clickId||undefined,firstSource:attribution.firstSource||undefined,firstMedium:attribution.firstMedium||undefined,firstCampaign:attribution.firstCampaign||undefined,firstContent:attribution.firstContent||undefined,firstTerm:attribution.firstTerm||undefined,firstClickId:attribution.firstClickId||undefined,firstReferralCode:attribution.firstReferralCode||undefined,idempotencyKey};trackEvent(`lead.${kind}.submit`,{cta:payload.cta,vehicleId:vehicle||undefined,metadata:{idempotencyKey}});const response=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify(payload)});const json=await response.json().catch(()=>({}));if(!response.ok)throw Error(json.error||"submit_failed");const leadId=String(json?.item?.id||json?.leadId||"");trackEvent(`lead.${kind}.accepted`,{cta:payload.cta,leadId:leadId||undefined,vehicleId:vehicle||undefined,metadata:{idempotencyKey,persisted:json?.persisted!==false,sync:json?.sync||null}});formEl.reset();setMessage(json?.sync?.upstream==="pending"?"Received. Your request is saved and queued for sync; Sean's team can see it now.":"Received. Sean's team will follow up shortly.");}catch(error){trackEvent(`lead.${kind}.failed`,{cta:source||`cta-${kind}`,metadata:{idempotencyKey,error:error instanceof Error?error.message:"submit_failed"}});setMessage(error instanceof Error&&error.message!=="submit_failed"?error.message:"We couldn't send this request. Please call 813-516-4752.");}finally{setBusy(false)}}
  return <form className="leadForm" onSubmit={submit}><div className="leadGrid"><label>Name<input name="name" autoComplete="name" maxLength={120} required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" inputMode="tel" maxLength={40}/></label><label>Email<input name="email" type="email" autoComplete="email" maxLength={160}/></label>{kind!=="contact"&&<label>Vehicle of interest<input name="vehicleInterest" maxLength={240}/></label>}{kind==="schedule"&&<label>Preferred date or time<input name="preferredTime" maxLength={120}/></label>}<label className="wide">Message<textarea name="message" maxLength={2000}/></label><label className="consent wide"><input name="consent" type="checkbox" required/> I agree WDCC may call, text, or email me about this request at the contact information I provided. Consent is not a condition of purchase. Message and data rates may apply.</label></div><button className="cta red" disabled={busy} type="submit">{busy?"SENDING…":"SEND REQUEST"}</button>{message&&<div className="leadMessage" role="status" aria-live="polite">{message}</div>}</form>;
}
