import Link from"next/link";
import TrackedCallLink from"./TrackedCallLink";
import{Footer,Header,Intro,VehicleGrid}from"./components";

export default function Home(){return <><Intro/><Header/><main>
<section className="premiumHero"><div className="heroPhoto" aria-hidden="true"/><div className="heroGlow" aria-hidden="true"/><div className="wrap heroContent"><div className="eyebrow">TAMPA BAY · DRIVE TODAY</div><h1><span className="redWord">BAD CREDIT?</span><br/><span className="blueWord">NO CREDIT?</span><br/>WE DON'T CARE.</h1><p className="lede">In-house financing. Listed down payments. Direct answers from Sean. Get on the road without the runaround.</p><div className="actions"><Link className="cta primary" href="/schedule-test-drive?source=hero-test-drive">SCHEDULE A TEST DRIVE →</Link><Link className="cta secondary" href="/get-approved?source=hero-preapproval">GET PRE-APPROVED →</Link><TrackedCallLink className="cta contact" source="hero-call-sean">CALL SEAN →</TrackedCallLink></div><div className="heroCall"><TrackedCallLink source="hero-phone">☎ CALL SEAN <b>813-516-4752</b></TrackedCallLink></div></div></section>
<section className="benefitBand"><div className="wrap"><div className="benefitGrid"><article><div className="benefitIcon">✓</div><strong>FAST ANSWERS</strong><span>Talk directly to Sean.</span></article><article><div className="benefitIcon">$</div><strong>LISTED DOWN PAYMENTS</strong><span>See the number before you call.</span></article><article><div className="benefitIcon">▣</div><strong>TEST DRIVE</strong><span>Choose a vehicle and a time.</span></article><article><div className="benefitIcon">◇</div><strong>FINANCING OPTIONS</strong><span>Final terms are subject to approval.</span></article></div></div></section>
<section className="section inventoryPremium"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow muted">FEATURED INVENTORY</div><h2>Vehicles ready now.</h2><p className="muted">Cash price and down payment shown clearly.</p></div><Link className="inventoryViewAll" href="/inventory">VIEW ALL INVENTORY →</Link></div><VehicleGrid limit={5}/></div></section>
<section id="how-it-works" className="financePremium"><div className="wrap"><h2>IN-HOUSE FINANCING. <em>WE MAKE IT EASY.</em></h2><div className="financeSteps"><article><div className="stepNum">1</div><b>START ONLINE</b><p>Send the basics in minutes.</p></article><article><div className="stepNum">2</div><b>TALK TO SEAN</b><p>Confirm your down payment and find the right vehicle fit.</p></article><article><div className="stepNum">3</div><b>CHOOSE YOUR CAR</b><p>Shop actual available inventory.</p></article><article><div className="stepNum">4</div><b>DRIVE TODAY</b><p>Schedule pickup or a test drive.</p></article></div></div></section>
<section className="trustPremium"><div className="wrap"><div className="trustLead"><div><div className="eyebrow">WHY CUSTOMERS CHOOSE WDCC</div><h2>REAL PEOPLE. REAL ANSWERS.</h2></div><TrackedCallLink className="trustCall" source="trust-call-sean">CALL OR TEXT SEAN<br/><b>813-516-4752</b></TrackedCallLink></div><div className="trust"><div><strong>REAL INVENTORY</strong><span>Dealer-published vehicles only.</span></div><div><strong>STRAIGHT ANSWERS</strong><span>Ask directly about pricing, fees and terms.</span></div><div><strong>DIRECT HELP</strong><span>Talk to Sean. Not a call center.</span></div><div><strong>SECURE PROCESS</strong><span>Your information is handled carefully.</span></div></div></div></section>
</main><Footer/></>}
