"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type V={id?:string;year?:number;make?:string;model?:string;trim?:string;price?:number;cashPrice?:number;downPayment?:number;down_payment?:number;down?:number;mileage?:number|string;engine?:string;cylinders?:string;primaryPhotoPathname?:string;primary_image_url?:string;photoUrl?:string;image?:string;archived?:boolean;status?:string};
const fallback:V[]=[
 {year:2020,make:"Dodge",model:"Challenger SXT",price:24995,downPayment:2000,mileage:"41K",engine:"V6"},
 {year:2019,make:"Dodge",model:"Charger R/T",price:21995,downPayment:1500,mileage:"53K",engine:"V8"},
 {year:2018,make:"Chevrolet",model:"Camaro LT",price:20995,downPayment:1500,mileage:"38K",engine:"V6"},
 {year:2020,make:"Jeep",model:"Grand Cherokee Laredo",price:23995,downPayment:2000,mileage:"60K",engine:"V6"},
 {year:2018,make:"Ford",model:"F-150 XLT",price:22995,downPayment:2000,mileage:"71K",engine:"V8"}
];
const money=(n?:number)=>n?"$"+Number(n).toLocaleString():"Call";
const title=(v:V)=>[v.year,v.make,v.model,v.trim].filter(Boolean).join(" ")||"Vehicle";
const img=(v:V,i:number)=>v.primaryPhotoPathname?`/api/media?p=${encodeURIComponent(v.primaryPhotoPathname)}`:v.primary_image_url||v.photoUrl||v.image||[`/assets/cars/2020-dodge-challenger-sxt-1.webp`,`/assets/cars/2019-dodge-charger-rt-1.webp`,`/assets/cars/2018-chevrolet-camaro-lt-1.webp`,`/assets/cars/2020-jeep-grand-cherokee-laredo-1.webp`,`/assets/cars/2018-ford-f150-xlt-1.webp`][i%5]||"/wdcc-hero-v2.webp";

export default function R31R25Home(){
 const[items,setItems]=useState<V[]>(fallback);const[menu,setMenu]=useState(false);const[intro,setIntro]=useState(true);
 useEffect(()=>{fetch("/api/inventory",{cache:"no-store"}).then(r=>r.json()).then(j=>{const a=(j.items||j.inventory||[]).filter((v:V)=>!v.archived&&String(v.status||"published").toLowerCase()!=="archived"&&Number(v.year||0)>1900&&v.make&&v.model);if(a.length)setItems(a.slice(0,8))}).catch(()=>{});const t=setTimeout(()=>setIntro(false),3000);return()=>clearTimeout(t)},[]);
 return <div className="r25" id="wdcc-r25-source-of-truth">
  <style dangerouslySetInnerHTML={{__html:css}}/>
  {intro&&<div className="r25-intro" onClick={()=>setIntro(false)}><div className="r25-intro-scene"/><div className="r25-smoke s1"/><div className="r25-smoke s2"/><img src="/wdcc-logo-transparent.webp" alt="We Don't Care Cars"/><p>TAMPA BAY · DRIVE TODAY</p><button onClick={()=>setIntro(false)}>SKIP INTRO</button></div>}
  <div className="top-strip"><div className="std"><span>TAMPA BAY</span><span>›</span><span>IN-HOUSE FINANCING</span><span>›</span><span>SEAN</span><span className="phone">813-516-4752</span></div></div>
  <header className="r25-header"><div className="std"><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Open menu">☰</button><Link className="brand" href="/"><img src="/wdcc-logo-transparent.webp" alt="We Don't Care Cars"/></Link><nav className={menu?"nav open":"nav"}><Link href="/inventory">Inventory</Link><Link href="/get-approved?source=header-financing">Financing</Link><a href="#how-it-works">How It Works</a><a href="#trust">Reviews</a><Link href="/contact?source=header-contact">About Us</Link></nav><div className="header-actions"><Link className="btn btn-red desktop-cta" href="/get-approved?source=header-get-approved">GET PRE-APPROVED</Link><a className="phone-round" href="tel:+18135164752">☎</a></div></div></header>
  <main>
   <section className="hero"><div className="std"><div className="hero-copy"><div className="eyebrow">Tampa Bay · Drive Today</div><h1><span className="red">BAD CREDIT?</span><br/><span className="blue">NO CREDIT?</span><br/><span className="white">WE DON'T CARE.</span></h1><p>In-house financing. Low down payments. Fast approvals. Straight answers. Get on the road without the runaround.</p><div className="hero-actions"><Link className="btn btn-red" href="/get-approved?source=hero-get-approved">GET PRE-APPROVED →</Link><Link className="btn btn-dark" href="/inventory">BROWSE INVENTORY →</Link></div><div className="call-line">☎ CALL SEAN <span>813-516-4752</span></div></div><div className="hero-art"><img src="/wdcc-hero-v2.webp" alt="American flag performance car in Tampa Bay"/></div></div></section>
   <section className="benefit-rail"><div className="std"><div className="benefit"><div className="ico">✓</div><b>Fast Approvals</b><p>Quick, straightforward decisions.</p></div><div className="benefit"><div className="ico">$</div><b>Low Down Payments</b><p>Options designed around real buyers.</p></div><div className="benefit"><div className="ico">▸</div><b>Drive Today</b><p>Move from interest to the road.</p></div><div className="benefit"><div className="ico">☆</div><b>Build Your Credit</b><p>Ask what programs may apply.</p></div></div></section>
   <section className="light" id="inventory"><div className="std"><div className="section-head"><div><div className="kicker">Featured Inventory</div><h2>Vehicles ready now.</h2><p>Cash price and down payment shown clearly.</p></div><Link className="text-link" href="/inventory">View all inventory →</Link></div><div className="inventory-grid">{items.slice(0,5).map((v,i)=><article className="vehicle-card" key={v.id||title(v)}><Link href={v.id?`/vehicle/${v.id}`:"/inventory"}><img src={img(v,i)} alt={title(v)}/></Link><div className="body"><h3>{title(v)}</h3><div className="price">{money(v.price||v.cashPrice)}</div><div className="down">{money(v.downPayment??v.down_payment??v.down??2000)} Down</div><div className="pills"><span className="pill">{typeof v.mileage==="number"?v.mileage.toLocaleString():v.mileage||"CALL"} MILES</span><span className="pill">{v.engine||v.cylinders||"AUTO"}</span></div></div></article>)}</div></div></section>
   <section className="finance" id="how-it-works"><div className="std"><div className="finance-head"><div><h2>IN-HOUSE FINANCING <span>MADE EASY</span></h2><p>One simple process. No hoops. No hassle.</p></div><Link className="btn btn-red" href="/get-approved?source=finance-start">START PRE-APPROVAL →</Link></div><div className="steps"><div className="step"><div className="num">1</div><b>Apply Online</b><p>Send basic details securely.</p></div><div className="step"><div className="num">2</div><b>Talk To Sean</b><p>Confirm down payment and vehicle fit.</p></div><div className="step"><div className="num">3</div><b>Choose Your Car</b><p>Shop our inventory online or in person.</p></div><div className="step"><div className="num">4</div><b>Drive Today</b><p>Schedule pickup or test drive.</p></div></div></div></section>
   <section className="trust" id="trust"><div className="std trust-grid"><div className="trust-item"><b>Tampa Bay Proud</b><p>Local dealer. Local community.</p></div><div className="trust-item"><b>Straight Answers</b><p>No runaround. No hidden fees.</p></div><div className="trust-item"><b>Real People</b><p>Talk to Sean. Not a call center.</p></div><div className="trust-item"><b>In-House Financing</b><p>We make it happen when others cannot.</p></div></div></section>
   <section className="close"><div className="std"><h2>READY TO DRIVE?</h2><p>Start the approval process or talk directly with Sean.</p><div className="hero-actions centered"><Link className="btn btn-red" href="/get-approved?source=close-get-approved">GET PRE-APPROVED</Link><a className="btn btn-dark" href="tel:+18135164752">TALK TO SEAN</a></div></div></section>
  </main><footer className="footer"><div className="std"><span>We Don't Care Cars</span><span>Sean: 813-516-4752</span><span>Tampa Bay, FL</span></div></footer>
  <div className="mobile-dock"><Link href="/schedule-test-drive?source=mobile-test-drive">TEST DRIVE</Link><Link href="/get-approved?source=mobile-get-approved">GET APPROVED</Link><a href="tel:+18135164752">CALL SEAN</a></div>
 </div>
}

const css=String.raw`
:root{--black:#03070B;--navy:#071522;--red:#EF2029;--blue:#168AF4;--gold:#E5B632;--off:#F7F7F5;--text:#101418;--muted:#66717D;--line:rgba(255,255,255,.10);--soft:rgba(15,25,35,.10)}
.r25,.r25 *{box-sizing:border-box}.r25{background:var(--black);color:#fff;font-family:Inter,Geist,"Helvetica Neue",Arial,sans-serif;overflow-x:hidden}.r25 a{text-decoration:none;color:inherit}.r25 img{max-width:100%;display:block}.std{width:min(1360px,calc(100% - 64px));margin:auto}.top-strip{height:34px;background:#020509;border-bottom:1px solid var(--line);font-size:12px;font-weight:800;letter-spacing:.11em;text-transform:uppercase;color:#dce4ed}.top-strip .std{height:34px;display:flex;align-items:center;justify-content:flex-end;gap:16px}.top-strip .phone{color:var(--red)}
.r25-header{background:rgba(3,7,11,.97);border-bottom:1px solid var(--line);position:relative;z-index:20}.r25-header .std{height:82px;display:flex;align-items:center;gap:32px}.brand img{height:78px;width:78px;object-fit:contain}.nav{display:flex;align-items:center;gap:30px;margin-left:10px;text-transform:uppercase;font-weight:900;font-size:13px;letter-spacing:.04em}.header-actions{margin-left:auto;display:flex;align-items:center;gap:14px}.btn{height:48px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;padding:0 24px;font-weight:900;text-transform:uppercase;letter-spacing:.03em;font-size:13px;border:1px solid transparent;white-space:nowrap;transition:.18s transform,.18s box-shadow}.btn:hover{transform:translateY(-1px)}.btn-red{background:var(--red);color:#fff}.btn-dark{background:rgba(0,0,0,.35);border-color:rgba(255,255,255,.45);color:#fff}.menu-btn,.phone-round{display:none}
.hero{background:radial-gradient(circle at 72% 42%,rgba(22,138,244,.18),transparent 36%),linear-gradient(90deg,#020509 0%,#05080d 45%,#07111d 100%);position:relative;overflow:hidden}.hero .std{min-height:690px;display:grid;grid-template-columns:42% 58%;align-items:center;gap:10px}.hero-copy{z-index:2;padding:42px 0}.eyebrow{display:flex;align-items:center;gap:12px;color:#78bfff;font-size:12px;text-transform:uppercase;font-weight:900;letter-spacing:.12em;margin-bottom:18px}.eyebrow:before{content:"";width:42px;height:3px;background:var(--gold);display:block}.hero h1{font-size:clamp(54px,5.2vw,86px);line-height:.92;letter-spacing:-.04em;margin:0 0 22px;font-weight:950;text-transform:uppercase}.red{color:var(--red)}.blue{color:var(--blue)}.white{color:#fff}.hero p{font-size:18px;line-height:1.55;max-width:540px;color:#eef3f8;margin:0 0 24px}.hero-actions{display:flex;gap:14px;align-items:center;margin-bottom:20px}.centered{justify-content:center}.call-line{font-weight:900;text-transform:uppercase}.call-line span{color:var(--red)}.hero-art{height:100%;min-height:620px;display:flex;align-items:center;justify-content:flex-end;position:relative}.hero-art:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#03070b 0%,rgba(3,7,11,.28) 28%,rgba(3,7,11,0) 62%);z-index:1}.hero-art img{width:100%;height:620px;object-fit:cover;object-position:center}
.benefit-rail{background:var(--off);color:var(--text)}.benefit-rail .std{transform:translateY(-38px);display:grid;grid-template-columns:repeat(4,1fr);background:#fff;border-radius:14px;box-shadow:0 12px 34px rgba(0,0,0,.13);overflow:hidden}.benefit{padding:28px 24px;text-align:center;border-right:1px solid rgba(15,25,35,.12)}.benefit:last-child{border-right:0}.benefit .ico{font-size:30px;color:var(--red);margin-bottom:10px}.benefit b{display:block;font-size:14px;text-transform:uppercase;margin-bottom:6px}.benefit p{font-size:13px;color:#56616d;margin:0;line-height:1.4}
.light{background:var(--off);color:var(--text);padding:34px 0 64px}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:26px}.kicker{text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:#66717d;font-size:12px}.section-head h2{font-size:34px;line-height:1;margin:6px 0 8px}.section-head p{margin:0;color:#66717d}.text-link{font-weight:950;text-transform:uppercase;font-size:13px}.inventory-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:18px}.vehicle-card{background:#fff;border:1px solid var(--soft);border-radius:14px;box-shadow:0 4px 18px rgba(0,0,0,.08);overflow:hidden}.vehicle-card img{width:100%;aspect-ratio:16/10;object-fit:cover;background:#111}.vehicle-card .body{padding:14px}.vehicle-card h3{font-size:16px;line-height:1.25;margin:0 0 10px}.price{font-size:24px;font-weight:950;margin-bottom:4px}.down{font-weight:800;color:#4c5965;font-size:13px;margin-bottom:10px}.pills{display:flex;gap:8px;flex-wrap:wrap}.pill{border:1px solid #d9dde1;border-radius:6px;padding:5px 8px;font-size:11px;font-weight:900}
.finance{background:#06111d;color:#fff;padding:70px 0}.finance-head{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:28px}.finance h2{font-size:38px;line-height:1;margin:0 0 10px;font-style:italic;text-transform:uppercase}.finance h2 span{color:var(--red)}.finance p{color:#cbd4dd;margin:0}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.step{background:#0b1a28;border:1px solid var(--line);border-radius:14px;padding:24px}.num{width:34px;height:34px;border-radius:50%;background:var(--red);display:flex;align-items:center;justify-content:center;font-weight:950;margin-bottom:18px}.step b{text-transform:uppercase;display:block;margin-bottom:8px}.step p{font-size:14px;color:#cbd4dd;line-height:1.45}
.trust{background:#fff;color:var(--text);padding:32px 0}.trust-grid{display:grid;grid-template-columns:repeat(4,1fr);border-radius:14px;overflow:hidden;border:1px solid var(--soft)}.trust-item{padding:24px;border-right:1px solid var(--soft)}.trust-item:last-child{border-right:0}.trust-item b{display:block;margin-bottom:6px;text-transform:uppercase}.close{background:#03070b;color:#fff;padding:70px 0;text-align:center}.close h2{font-size:50px;margin:0 0 10px}.footer{background:#020509;color:#9aa5b1;border-top:1px solid var(--line);padding:28px 0;font-size:13px}.footer .std{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.mobile-dock{display:none}
.r25-intro{position:fixed;inset:0;z-index:9999;background:#020305;overflow:hidden;cursor:pointer}.r25-intro-scene{position:absolute;inset:-2%;background:linear-gradient(90deg,rgba(2,5,9,.85),rgba(2,5,9,.08)),url('/wdcc-hero-v2.webp') 70% center/cover no-repeat;animation:scene 2.65s cubic-bezier(.16,1,.3,1) both}.r25-intro>img{position:absolute;z-index:4;left:50%;top:48%;width:min(28vw,300px);transform:translate(-50%,-50%);filter:drop-shadow(0 0 30px rgba(22,138,244,.3));animation:logo .7s .12s both}.r25-intro>p{position:absolute;z-index:5;left:0;right:0;bottom:12%;text-align:center;letter-spacing:.22em;font-size:10px;font-weight:900}.r25-intro>button{position:absolute;z-index:6;right:18px;bottom:18px;background:#020509aa;border:1px solid #ffffff45;border-radius:999px;color:#fff;padding:10px 14px}.r25-smoke{position:absolute;z-index:2;border-radius:50%;filter:blur(34px);opacity:0}.s1{left:5%;bottom:-8%;width:58%;height:40%;background:radial-gradient(circle,#ffffff31,transparent 66%);animation:smoke 2.4s .15s both}.s2{right:-5%;bottom:-10%;width:50%;height:42%;background:radial-gradient(circle,#168af43b,transparent 66%);animation:smoke 2.6s .3s both}@keyframes scene{from{opacity:.2;transform:scale(1.08)}to{opacity:1;transform:scale(1)}}@keyframes logo{from{opacity:0;transform:translate(-50%,-50%) scale(.72)}to{opacity:1;transform:translate(-50%,-50%) scale(1)}}@keyframes smoke{0%{opacity:0;transform:scale(.7)}35%{opacity:.75}100%{opacity:0;transform:scale(1.55) translateY(-12%)}}
@media(max-width:1023px){.std{width:min(calc(100% - 40px),720px)}.top-strip .std{justify-content:center}.r25-header .std{height:76px;gap:14px;justify-content:space-between}.brand img{height:64px;width:64px}.nav,.desktop-cta{display:none}.nav.open{display:flex;position:absolute;top:76px;left:0;right:0;background:#03070bf7;flex-direction:column;align-items:stretch;padding:18px 24px;margin:0;z-index:30}.nav.open a{padding:13px 0;border-bottom:1px solid var(--line)}.menu-btn,.phone-round{display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;border-radius:12px;border:1px solid var(--line);background:#07111d;color:#fff;font-weight:900}.phone-round{background:var(--red);border-color:var(--red);border-radius:50%}.hero .std{width:100%;min-height:auto;display:flex;flex-direction:column;padding:0}.hero-copy{order:2;width:100%;padding:34px 24px}.hero-art{order:1;width:100%;height:auto;min-height:0}.hero-art:before{background:linear-gradient(180deg,rgba(3,7,11,0) 35%,#03070b 98%)}.hero-art img{height:330px;object-position:center}.hero h1{font-size:clamp(42px,12vw,58px);max-width:94vw}.hero p{font-size:16px}.hero-actions{display:grid;grid-template-columns:1fr;gap:12px}.btn{width:100%;height:54px}.benefit-rail .std{width:100%;transform:none;border-radius:0;grid-template-columns:repeat(4,180px);overflow-x:auto}.light{padding:42px 0}.section-head{align-items:flex-start}.inventory-grid{display:flex;overflow-x:auto;gap:14px;padding-bottom:10px}.vehicle-card{min-width:72vw}.finance-head{display:block}.finance-head .btn{margin-top:20px}.steps,.trust-grid{grid-template-columns:1fr}.trust-item{border-right:0;border-bottom:1px solid var(--soft)}.mobile-dock{position:fixed;bottom:0;left:0;right:0;z-index:50;background:#03070bf6;border-top:1px solid #24384b;padding:8px;display:grid;grid-template-columns:1.1fr 1fr .8fr;gap:7px}.mobile-dock a{min-height:50px;border-radius:9px;border:1px solid #385166;display:grid;place-items:center;font-size:9px;font-weight:900}.mobile-dock a:first-child{background:var(--red);border-color:#ff5962}.mobile-dock a:nth-child(2){background:#0b2a41}.r25{padding-bottom:66px}.r25-intro>img{width:min(62vw,230px)}}
`;
